# Generated by Django 5.2.11 on 2026-03-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_post_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="service_type",
        ),
    ]
