# Generated by Django 5.2.11 on 2026-03-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_post_created_at"),
        ("core", "0006_remove_post_service_type"),
    ]

    operations = []
