# Generated by Django 6.0.2 on 2026-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_problemreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
