# Generated by Django 5.2.11 on 2026-03-21 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_repair_erp_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("experience", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=50)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("available_person", models.PositiveIntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertises",
                        to="core.post",
                    ),
                ),
            ],
        ),
    ]
