# Generated by Django 5.2.11 on 2026-03-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_expertise"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertise",
            name="experience_unit",
            field=models.CharField(
                choices=[
                    ("day", "Day"),
                    ("month", "Month"),
                    ("year", "Year"),
                    ("hour", "Hour"),
                ],
                default="year",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expertise",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
