# Generated by Django 5.2.11 on 2026-03-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_expertise_experience_unit_alter_expertise_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertise",
            name="experience_unit",
        ),
    ]
