# Generated by Django 5.2.11 on 2026-03-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_expertise_experience_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertise",
            name="experience",
            field=models.CharField(max_length=100),
        ),
    ]
