# Generated by Django 5.2.11 on 2026-04-02 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_post_website_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="connection_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("expertise", "Expertise"),
                    ("skill_provider", "Skill Provider"),
                    ("supplier", "Delivery Man"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("connection_request", "Connection Request"),
                    ("connection_accepted", "Connection Accepted"),
                    ("connection_rejected", "Connection Rejected"),
                    ("connection_removed", "Connection Removed"),
                ],
                default="connection_request",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications_related_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
